### ISSUE TITLE
ImportError: cannot import name 'deform_conv_cuda'

### ISSUE THREAD

**Issue by StoicGilgamesh** [uber-research/UPSNet#105]
First of all thanks for this great research and the repository! Very helpful.

I have followed the instructions but when I try to train or test using pre-trained weights I get the following error. Could you please help?

upsnet/../upsnet/config/config.py:180: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  exp_config = edict(yaml.load(f))
Traceback (most recent call last):
  File "upsnet/upsnet_end2end_test.py", line 44, in <module>
    from upsnet.models import *
  File "upsnet/../upsnet/models/__init__.py", line 1, in <module>
    from .resnet_upsnet import resnet_50_upsnet, resnet_101_upsnet
  File "upsnet/../upsnet/models/resnet_upsnet.py", line 22, in <module>
    from upsnet.models.resnet import get_params, resnet_rcnn, ResNetBackbone
  File "upsnet/../upsnet/models/resnet.py", line 21, in <module>
    from upsnet.operators.modules.deform_conv import DeformConv
  File "upsnet/../upsnet/operators/modules/deform_conv.py", line 22, in <module>
    from upsnet.operators.functions.deform_conv import DeformConvFunction
  File "upsnet/../upsnet/operators/functions/deform_conv.py", line 21, in <module>
    from .._ext.deform_conv import deform_conv_cuda
ImportError: cannot import name 'deform_conv_cuda'
(/scratch_net/biwidl204/hgupta/anaconda/conda_envs/py36

**Comment by SunNYNO1** [comment]
I meet the same problem，do you solve this problem？ could you help me？

**Comment by StoicGilgamesh** [comment]
For me, the problem was with my Cuda settings and PyTorch version on the cluster. PyTorch was not able to recognize GPUS.

**Comment by SunNYNO1** [comment]
thank you very much, but I  find the github dont have the deform_conv_cuda.py under the path, do you know why, thanks again ------------------ 原始邮件 ------------------
发件人: "Hrishikesh Gupta"<notifications@github.com>
发送时间: 2019年11月19日(星期二) 晚上6:18
收件人: "uber-research/UPSNet"<UPSNet@noreply.github.com>;
抄送: "sun"<1246680611@qq.com>;"Comment"<comment@noreply.github.com>;
主题: Re: [uber-research/UPSNet] ImportError: cannot import name'deform_conv_cuda' (#105)



For me, the problem was with my Cuda settings and PyTorch version on the cluster. PyTorch was not able to recognize GPUS.
 
&mdash;

**Comment by moshuilanting** [comment]
init.sh 编译的时候应该就存在问题，进到operators重新编译build_deform_conv.py

cd ../operators
python build_deform_conv.py build_ext --inplace 

我会报这个错误 "error: ‘THCState_getCurrentStream’ was not declared in this scope"
找到对应行把“THCState_getCurrentStream(state)”都替换为c10::cuda::getCurrentCUDAStream()，这个问题就没了

**Comment by Sujan-PhdWork** [comment]
this configuration worked for me
`conda install pytorch==1.1.0 torchvision==0.3.0 cudatoolkit=9.0 -c pytorch
`
