### ISSUE TITLE
About your coco id and labels

### ISSUE THREAD

**Issue by JoyHuYY1412** [uber-research/UPSNet#42]
I noticed that you make the categories sorted as `0-52:stuff,53-132:things` in creating `panoptic_coco_categories_stff.json`. Why you do this change?

So when you print out the result matrix like this format:

> IDX |    PQ    SQ    RQ    IoU      TP      FP      FN

Does the` IDX 0` mean the result for the first thing class or the first stuff class?
Similarly, how about other metrics like `the Mean and per-category AP`? The first line represent the first thing class or first stuff class?

I really appreciate your reply.

**Comment by YuwenXiong** [comment]
We change class order in order to make it consistent with cityscapes (stuff first, then things). 
And all results follow the setting (so IDX 0 means the first stuff class). 
AP is only for things so the first line is for the first thing class. 
If you want to submit test-dev result you need to do some change on prediction.
